name: Compilar APK Android

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o código
      uses: actions/checkout@v4

    - name: Configurar Java (JDK 17)
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Dar permissão ao Gradle
      run: chmod +x ./gradlew

    - name: Compilar o app com Gradle
      run: ./gradlew assembleDebug

    - name: Salvar o APK como artefato
      uses: actions/upload-artifact@v4
      with:
        name: QuiZoeiraApp-debug
        path: app/build/outputs/apk/debug/app-debug.apk
